language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - python3 manage.py migrate

script:
  - pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $ACCESS_KEY
  region: "us-east-1"
  app: "mysite"
  env: "mysite-dev"
  bucket_name: "http://mysite-dev22.us-east-1.elasticbeanstalk.com/"
  bucket_path: "polls/"
  on:
    repo: esiino1/swe1
    branch: main